include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml

  # Main pipeline - skip when RENOVATE_RUN=true
  - local: '.gitlab/ci/main-pipeline.yml'
    rules:
      - if: '$RENOVATE_RUN == "true"'
        when: never
      - when: always

  # Renovate pipeline - only when RENOVATE_RUN=true for example during scheduled pipeline
  - local: '.gitlab/ci/renovate.yml'
    rules:
      - if: '$RENOVATE_RUN == "true"'
