repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix" ]
      - id: trailing-whitespace
        exclude: ".*wallet"
      - id: end-of-file-fixer
        exclude: ".*wallet|.*profile|.*backup"
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-lock
        name: checking if poetry.lock is consistent with pyproject.toml
        language_version: python3.12
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: format stylesheets using prettier
        files: \.(scss)$
        additional_dependencies:
          - 'prettier@2.8.8'
          - '@azabraao/prettier-plugin-css-order@1.3.0'
        args: [ "--print-width", "120", "--plugin=@azabraao/prettier-plugin-css-order" ]
      - id: prettier
        name: pretty format markdown
        additional_dependencies: [ 'prettier@2.8.8' ]
        files: \.md$
        args:
          - "--print-width"
          - "120"
          - "--prose-wrap"
          - "always"
          - "--tab-width"
          - "4"
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.2.1
    hooks:
      - id: stylelint
        name: lint and autoformat stylesheets using stylelint
        files: \.(scss)$
        additional_dependencies:
          # stylelint itself needs to be here when using additional_dependencies.
          - stylelint@16.2.1
          - stylelint-config-standard-scss@13.0.0
        args: [ "--fix" ]
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.6
    hooks:
      - id: pydoclint
        name: check docstrings with pydoclint
        entry: "pydoclint clive/ tests/ testnet_node.py"
        pass_filenames: false
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.11.5'
    hooks:
      - id: ruff
        name: linting code with Ruff
        args: [ "--fix" ]
      - id: ruff-format
        name: format code using Ruff formatter
  - repo: local
    hooks:
    - id: mypy
      name: type check with mypy
      entry: mypy
      language: system
      types: [ python ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
      args: ["--skip=clive/__private/core/accounts/bad_accounts_list.txt"]
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args:
          - "--create"
          - "--python-folders"
          - "\
            tests/clive-local-tools/clive_local_tools,\
            tests/functional/,\
            tests/tui/,\
            tests/unit/,\
            clive,
            "
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      -  id: shellcheck
