repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix" ]
        exclude: ".*alternate-chain-spec.json"
      - id: trailing-whitespace
        exclude: ".*_pattern.txt|.*wallet"
      - id: end-of-file-fixer
        exclude: ".*_pattern.txt|.*config.ini|.*alternate-chain-spec.json|.*timestamp|.*wallet"
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-lock
        name: checking if poetry.lock is consistent with pyproject.toml
        args: [ "--no-update" ]
        language_version: python3.10
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: format stylesheets using prettier
        files: \.(scss)$
        additional_dependencies:
          - 'prettier@2.8.8'
          - '@azabraao/prettier-plugin-css-order@1.3.0'
        args: [ "--print-width", "120", "--plugin=@azabraao/prettier-plugin-css-order" ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.2.2'
    hooks:
      - id: ruff
        name: linting code with Ruff
        args: [ "--fix" ]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        name: format code using black
  - repo: local
    hooks:
    - id: mypy
      name: type check with mypy
      entry: mypy
      language: system
      types: [ python ]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args:
          - "--create"
          - "--python-folders"
          - "\
            tests/clive-local-tools/clive_local_tools,\
            tests/functional/,\
            tests/tui/,\
            tests/unit/,\
            clive,
            "
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      -  id: shellcheck
