FROM registry.gitlab.syncad.com/hive/hive/ci-base-image:ubuntu22.04-3

ADD . /clive
WORKDIR /clive

ARG HIVED_LOCATION
ADD $HIVED_LOCATION /clive/hived
ENV HIVED_PATH=/clive/hived

ARG BEEKEEPER_LOCATION
ADD ${BEEKEEPER_LOCATION} /clive/beekeeper

RUN poetry self update

RUN poetry install

# crucial for proper display
ENV COLORTERM=truecolor

ENTRYPOINT [ "poetry", "run", "python", "testnet_node.py", "&>", "/dev/null", "&", "poetry", "run", "clive" ]
