[default.style]
gray = "#858585"
blue = "#285dff"
green = "#00903e"
primary = "@format bg:{this.style.GRAY}"
secondary = "@format bg:{this.style.BLUE}"
tertiary = "@format bg:{this.style.GREEN}"
button = "@format bg:{this.style.BLUE}"
"button.focused" = "fg:#000000"
