"""File with available operations and matching buttons"""
from __future__ import annotations

from typing import TYPE_CHECKING, Final

from clive.__private.ui.operations import (
    AccountCreate,
    AccountUpdate,
    AccountUpdate2,
    AccountWitnessProxy,
    AccountWitnessVote,
    CancelTransferFromSavings,
    ChangeRecoveryAccount,
    ClaimAccount,
    ClaimRewardBalance,
    CollateralizedConvert,
    Comment,
    CommentOptions,
    Convert,
    CreateClaimedAccount,
    CreateProposal,
    Custom,
    CustomJson,
    DeleteComment,
    EscrowDispute,
    EscrowRelease,
    EscrowTransfer,
    FeedPublish,
    LimitOrderCancel,
    LimitOrderCreate,
    LimitOrderCreate2,
    RecoverAccount,
    RecurrentTransfer,
    RemoveProposal,
    RequestAccountRecovery,
    SetWithdrawVestingRoute,
    TransferFromSavings,
    TransferToAccount,
    TransferToSavings,
    TransferToVesting,
    UpdateProposal,
    UpdateProposalVotes,
    Vote,
    WithdrawVesting,
    WitnessSetProperties,
    WitnessUpdate,
)

if TYPE_CHECKING:
    from clive.__private.ui.operations.operation_base import OperationBase

OPERATIONS: Final[list[type[OperationBase]]] = [
    TransferToAccount,
    TransferToSavings,
    Vote,
    Convert,
    AccountWitnessVote,
    TransferToVesting,
    AccountWitnessProxy,
    CancelTransferFromSavings,
    ChangeRecoveryAccount,
    ClaimAccount,
    WithdrawVesting,
    UpdateProposalVotes,
    UpdateProposal,
    TransferFromSavings,
    SetWithdrawVestingRoute,
    RemoveProposal,
    RecurrentTransfer,
    LimitOrderCreate,
    LimitOrderCancel,
    EscrowTransfer,
    EscrowRelease,
    EscrowDispute,
    DeleteComment,
    Custom,
    CustomJson,
    CreateProposal,
    CommentOptions,
    Comment,
    ClaimRewardBalance,
    WitnessUpdate,
    WitnessSetProperties,
    RequestAccountRecovery,
    RecoverAccount,
    LimitOrderCreate2,
    FeedPublish,
    CreateClaimedAccount,
    AccountCreate,
    AccountUpdate,
    AccountUpdate2,
    CollateralizedConvert,
]
