"""File with available operations and matching buttons"""
from __future__ import annotations

from typing import TYPE_CHECKING, Final

from clive.__private.ui.operations import (
    AccountWitnessProxy,
    AccountWitnessVote,
    CancelTransferFromSavings,
    ChangeRecoveryAccount,
    ClaimAccount,
    ClaimRewardBalance,
    Comment,
    CommentOptions,
    Convert,
    CreateProposal,
    Custom,
    CustomJson,
    DeclineVotingRights,
    DelegateVestingShares,
    DeleteComment,
    EscrowApprove,
    EscrowDispute,
    EscrowRelease,
    EscrowTransfer,
    FeedPublish,
    LimitOrderCancel,
    LimitOrderCreate,
    LimitOrderCreate2,
    RecoverAccount,
    RecurrentTransfer,
    RemoveProposal,
    RequestAccountRecovery,
    ResetAccount,
    SetResetAccount,
    SetWithdrawVestingRoute,
    TransferFromSavings,
    TransferToAccount,
    TransferToSavings,
    TransferToVesting,
    UpdateProposal,
    UpdateProposalVotes,
    Vote,
    WithdrawVesting,
    WitnessBlockApprove,
    WitnessSetProperties,
    WitnessUpdate,
)

if TYPE_CHECKING:
    from clive.__private.ui.operations.cart_based_screen.cart_based_screen import OperationBase


OPERATIONS: Final[list[type[OperationBase]]] = [
    TransferToAccount,
    TransferToSavings,
    Vote,
    Convert,
    AccountWitnessVote,
    WitnessBlockApprove,
    TransferToVesting,
    AccountWitnessProxy,
    CancelTransferFromSavings,
    ChangeRecoveryAccount,
    ClaimAccount,
    WithdrawVesting,
    UpdateProposalVotes,
    UpdateProposal,
    TransferFromSavings,
    SetWithdrawVestingRoute,
    SetResetAccount,
    RemoveProposal,
    RecurrentTransfer,
    LimitOrderCreate,
    LimitOrderCancel,
    EscrowTransfer,
    EscrowRelease,
    EscrowDispute,
    EscrowApprove,
    DeleteComment,
    DelegateVestingShares,
    DeclineVotingRights,
    Custom,
    CustomJson,
    CreateProposal,
    CommentOptions,
    Comment,
    ClaimRewardBalance,
    WitnessUpdate,
    WitnessSetProperties,
    ResetAccount,
    RequestAccountRecovery,
    RecoverAccount,
    LimitOrderCreate2,
    FeedPublish,
]
