from __future__ import annotations

import typer

from clive.__private.cli.clive_typer import CliveTyper
from clive.__private.cli.common.parameters.argument_related_options import _make_argument_related_option
from clive.__private.cli.common.parameters.ensure_single_value import EnsureSingleValue
from clive.__private.core.constants.cli import REQUIRED_AS_ARG_OR_OPTION

generate = CliveTyper(name="generate", help="Commands for generating keys.")


_account_name_argument = typer.Argument(
    None,
    help=(f"Account for which key is derived, this is not working account of profile. ({REQUIRED_AS_ARG_OR_OPTION})"),
    show_default=False,
)

_role_argument = typer.Argument(
    None,
    help=(
        "Role for which key is derived. Usually should be one of: owner, active, posting, memo"
        f" but other values are allowed. ({REQUIRED_AS_ARG_OR_OPTION})"
    ),
    show_default=False,
)


@generate.command()
async def key_from_seed(  # noqa: PLR0913
    account_name: str | None = _account_name_argument,
    account_name_option: str | None = _make_argument_related_option("--account-name"),
    role: str | None = _role_argument,
    role_option: str | None = _make_argument_related_option("--role"),
    only_private_key: bool = typer.Option(  # noqa: FBT001
        default=False, help="Whether to display only the private key instead of key pair."
    ),
    only_public_key: bool = typer.Option(  # noqa: FBT001
        default=False, help="Whether to display only the public key instead of key pair."
    ),
) -> None:
    """
    Derive private key by hashing account-name, role and seed.

    Seed should be given at stdin (possibly in non tty mode i.e. piped),
    parameters `account-name` and `role` are positional arguments or options.
    This can be for example phrase generated by `clive generate secret-phrase`.
    """
    from clive.__private.cli.commands.generate import KeyFromSeed  # noqa: PLC0415

    await KeyFromSeed(
        account_name=EnsureSingleValue("account-name").of(account_name, account_name_option),
        role=EnsureSingleValue("role").of(role, role_option),
        only_private_key=only_private_key,
        only_public_key=only_public_key,
    ).run()


@generate.command()
async def public_key() -> None:
    """Display the public key that corresponds to the private key provided at stdin."""
    from clive.__private.cli.commands.generate import PublicKey  # noqa: PLC0415

    await PublicKey().run()


@generate.command()
async def random_key(
    key_pairs: int = typer.Argument(default=1, help="Amount of key pairs to generate."),
    key_pairs_option: int | None = _make_argument_related_option("--key-pairs"),
) -> None:
    """Generate random key pairs (a private key and its corresponding public key)."""
    from clive.__private.cli.commands.generate import RandomKey  # noqa: PLC0415

    await RandomKey(key_pairs=EnsureSingleValue[int]("key-pairs").of(key_pairs, key_pairs_option)).run()


@generate.command()
async def secret_phrase() -> None:
    """
    Suggest 16 words (brain key) that can be used to derive private keys.

    Secret key can be stored offline and its easier to store key then all private keys
    in wallet import format (wif). Private key is derived from hashing brain key + role.
    Knowing secret key means knowing all other keys.
    For example use command `clive generate private-key-from-seed --account-name alice --role active`
    and enter brain key as stdin to get active private key enerated from this secret key.
    """
    from clive.__private.cli.commands.generate import SecretPhrase  # noqa: PLC0415

    await SecretPhrase().run()
