from __future__ import annotations

from decimal import Decimal
from math import floor, log10
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Final


MAX_NUMBER_OF_PROPOSAL_IDS_IN_SINGLE_OPERATION: Final[int] = 5
HIVE_PERCENT_PRECISION: Final[int] = 100
HIVE_PERCENT_PRECISION_DOT_PLACES: Final[int] = floor(log10(HIVE_PERCENT_PRECISION))

VESTS_TO_HIVE_RATIO_PRECISION: Final[int] = 1000
VESTS_TO_HIVE_RATIO_PRECISION_DOT_PLACES: Final[int] = floor(log10(VESTS_TO_HIVE_RATIO_PRECISION))

NULL_ACCOUNT_KEY_VALUE: Final[str] = "STM1111111111111111111111111111111114T1Anm"
PARTICIPATION_CALCULATION_SLOTS_COUNT: Final[int] = 128

VESTS_REMOVE_DELEGATION_AMOUNT: Final[int] = 0
VESTS_REMOVE_POWER_DOWN_AMOUNT: Final[int] = 0
PERCENT_REMOVE_WITHDRAW_ROUTE_AMOUNT: Final[Decimal] = Decimal(0)
HIVE_FEE_TO_USE_RC_IN_CLAIM_ACCOUNT_TOKEN_OPERATION: Final[int] = 0
