from __future__ import annotations

from math import floor, log10
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Final


MAX_NUMBER_OF_PROPOSAL_IDS_IN_SINGLE_OPERATION: Final[int] = 5
HIVE_PERCENT_PRECISION: Final[int] = 100
HIVE_PERCENT_PRECISION_DOT_PLACES: Final[int] = floor(log10(HIVE_PERCENT_PRECISION))

VESTS_TO_HIVE_RATIO_PRECISION: Final[int] = 1000
VESTS_TO_HIVE_RATIO_PRECISION_DOT_PLACES: Final[int] = floor(log10(VESTS_TO_HIVE_RATIO_PRECISION))

NULL_ACCOUNT_KEY_VALUE: Final[str] = "STM1111111111111111111111111111111114T1Anm"
PARTICIPATION_CALCULATION_SLOTS_COUNT: Final[int] = 128
