from __future__ import annotations

import typer

from clive.__private.cli.clive_typer import CliveTyper
from clive.__private.cli.common.parameters.argument_related_options import _make_argument_related_option
from clive.__private.cli.common.parameters.argument_related_options import (
    account_name as account_name_argument_related_option,
)
from clive.__private.cli.common.parameters.ensure_single_value import EnsureSingleValue
from clive.__private.cli.common.parameters.styling import stylized_help
from clive.__private.core.types import AuthorityLevel

call = CliveTyper(name="call", help="Invoke api methods.")


@call.callback(invoke_without_command=True)
async def api(  # noqa: PLR0913
    api_name: str = typer.Argument(
        ...,
        help="api name",
    ),
    function_name: str = typer.Argument(
        ...,
        help="method name",
    ),
    api_params: list[str] | None = typer.Argument(
        None,
        help="arg-name=arg-value pairs for the api method",
    ),
) -> None:
    """
    Derive private key by hashing account-name, role and seed.

    Seed (like a secret phrase) should be given at stdin (possibly in a non interactive mode i.e. piped).
    This can be for example phrase generated by `clive generate secret-phrase`.
    """
    from clive.__private.cli.commands.call.call import Call  # noqa: PLC0415

    await Call(
        api_name=api_name,
        function_name=function_name,
        api_params=api_params if api_params is not None else [],
    ).run()

