from __future__ import annotations

from typing import Final

DATA_PATH: Final[str] = "DATA_PATH"
MAX_NUMBER_OF_TRACKED_ACCOUNTS: Final[str] = "MAX_NUMBER_OF_TRACKED_ACCOUNTS"

IS_DEV: Final[str] = "IS_DEV"
LOG_DEBUG_LOOP: Final[str] = "LOG_DEBUG_LOOP"
LOG_DEBUG_PERIOD_SECS: Final[str] = "LOG_DEBUG_PERIOD_SECS"

LOG_DIRECTORY: Final[str] = "LOG_DIRECTORY"
LOG_PATH: Final[str] = "LOG_PATH"
LOG_KEEP_HISTORY: Final[str] = "LOG_KEEP_HISTORY"
LOG_LEVELS: Final[str] = "LOG_LEVELS"
LOG_LEVEL_1ST_PARTY: Final[str] = "LOG_LEVEL_1ST_PARTY"
LOG_LEVEL_3RD_PARTY: Final[str] = "LOG_LEVEL_3RD_PARTY"

BEEKEEPER_REMOTE_ADDRESS: Final[str] = "BEEKEEPER.REMOTE_ADDRESS"
BEEKEEPER_COMMUNICATION_TOTAL_TIMEOUT_SECS: Final[str] = "BEEKEEPER.COMMUNICATION_TOTAL_TIMEOUT_SECS"
BEEKEEPER_COMMUNICATION_ATTEMPTS_AMOUNT: Final[str] = "BEEKEEPER.COMMUNICATION_ATTEMPTS_AMOUNT"
BEEKEEPER_COMMUNICATION_RETRIES_DELAY_SECS: Final[str] = "BEEKEEPER.COMMUNICATION_RETRIES_DELAY_SECS"
BEEKEEPER_REFRESH_TIMEOUT_SECS: Final[str] = "BEEKEEPER.REFRESH_TIMEOUT_SECS"
BEEKEEPER_SESSION_TOKEN: Final[str] = "BEEKEEPER.SESSION_TOKEN"
BEEKEEPER_INITIALIZATION_TIMEOUT: Final[str] = "BEEKEEPER.INITIALIZATION_TIMEOUT"
BEEKEEPER_CLOSE_TIMEOUT: Final[str] = "BEEKEEPER.CLOSE_TIMEOUT"

NODE_CHAIN_ID: Final[str] = "NODE.CHAIN_ID"
NODE_REFRESH_RATE_SECS: Final[str] = "NODE.REFRESH_RATE_SECS"
NODE_REFRESH_ALARMS_RATE_SECS: Final[str] = "NODE.REFRESH_ALARMS_RATE_SECS"
NODE_COMMUNICATION_TOTAL_TIMEOUT_SECS: Final[str] = "NODE.COMMUNICATION_TOTAL_TIMEOUT_SECS"
NODE_COMMUNICATION_ATTEMPTS_AMOUNT: Final[str] = "NODE.COMMUNICATION_ATTEMPTS_AMOUNT"
NODE_COMMUNICATION_RETRIES_DELAY_SECS: Final[str] = "NODE.COMMUNICATION_RETRIES_DELAY_SECS"

SECRETS_NODE_ADDRESS: Final[str] = "SECRETS.NODE_ADDRESS"
SECRETS_DEFAULT_PRIVATE_KEY: Final[str] = "SECRETS.DEFAULT_PRIVATE_KEY"
