stages:
  - maintenance

default:
  tags:
    - public-runner-docker

renovate:
  stage: maintenance
  image: renovate/renovate:42.92
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: https://gitlab.syncad.com/api/v4
    RENOVATE_REPOSITORIES: hive/clive
    RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate@syncad.com>"
    RENOVATE_ONBOARDING: "false"
    RENOVATE_REQUIRE_CONFIG: "optional"
    RENOVATE_CONFIG_FILE: "renovate.json"
    RENOVATE_BASE_BRANCHES: '["mzebrak/renovate"]'
    RENOVATE_USE_BASE_BRANCH_CONFIG: "merge"
    RENOVATE_PRUNE_STALE_BRANCHES: "false"
    LOG_LEVEL: info
    LOG_FILE: renovate.log
    LOG_FILE_LEVEL: debug
  script:
    - renovate --token="${RENOVATE_TOKEN}"
  artifacts:
    paths:
      - renovate.log
    expire_in: 1 week
    when: always
