stages:
  - maintenance

default:
  tags:
    - public-runner-docker

renovate:
  stage: maintenance
  image: renovate/renovate:42.99
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: https://gitlab.syncad.com/api/v4
    RENOVATE_REPOSITORIES: hive/clive
    RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate@syncad.com>"
    LOG_LEVEL: info
    LOG_FILE: renovate.log
    LOG_FILE_LEVEL: debug
  before_script:
    - |
      for var in RENOVATE_TOKEN GITHUB_COM_TOKEN; do
        if [ -z "${!var}" ]; then
          echo "Error: ${var} is not set"
          exit 1
        fi
      done
  script:
    - renovate
  artifacts:
    paths:
      - renovate.log
    expire_in: 1 week
    when: always
